alias alias.delete='unalias'
alias alias.edit='$EDITOR ~/.bash_aliases'
alias alias.list='alias'
alias alias.list.terse='alias.list | cut -d " " -f 2- | cut -d "=" -f1'
alias alias.new='alias'
alias alias.reload='. ~/.bash_aliases'
alias alias.save='alias > ~/.bash_aliases'
alias apt-get='sudo apt-get'
alias blkid='sudo blkid'
alias cls='clear'
alias cp='cp -i'
alias dir='ls -la'
alias dir.change='cd'
alias dir.contents='ls'
alias dir.contents.long='dir.contents -la'
alias dir.current='pwd'
alias dir.delete='rmdir'
alias dir.list='ls'
alias dir.list.help='ls --help'
alias dir.move='mv'
alias dir.new='mkdir'
alias dir.properties='stat'
alias dir.remove='rmdir'
alias dir.rename='mv'
alias dir.stat='stat'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias file.contents='cat'
alias file.contents.backwards='tac'
alias file.contents.pager='less'
alias file.contents.reverse='rev'
alias file.cut='cut'
alias file.delete='rm'
alias file.grep='grep'
alias file.head='head'
alias file.join='join'
alias file.move='mv'
alias file.new='touch'
alias file.paste='paste'
alias file.properties='stat'
alias file.rename='mv'
alias file.sort='sort'
alias file.stat='stat'
alias file.tail='tail'
alias file.type='file'
alias function.delete='unset -f'
alias function.edit='$EDITOR ~/.bash_functions'
alias function.list.detailed='declare -f'
alias function.list.terse='declare -F | cut -d "=" -f2- '
alias function.new='function'
alias function.reload='. ~/.bash_functions'
alias function.save='declare -f > ~/.bash_functions '
alias grep='grep --color=auto'
alias groups.list='cut -d: -f1 /etc/group'
alias groups.list.long='tr : "\t" < /etc/group'
alias h='history'
alias l='ls -CF'
alias l.='ls .[a-zA-Z]* --color=tty'
alias la='ls -A'
alias less='less -iX -S -# 10'
alias ll='ls -l --color=tty'
alias ls='ls --color=tty'
alias more='less'
alias mv='mv -i'
alias open='gnome-open '
alias path='echo $PATH'
alias pause='kill -19'
alias pd='cd -'
alias perl='perl -MEnglish -w'
alias poing='ping'
alias rehash='hash -r'
alias resume='kill -18'
alias rm='rm -i'
alias root='sudo su -'
alias s3cmd.bucket.create='s3cmd mb '
alias s3cmd.bucket.delete='s3cmd rb '
alias s3cmd.bucket.info='s3cmd ib '
alias s3cmd.bucket.list='s3cmd ls '
alias s3cmd.bucket.size='s3cmd du'
alias s3cmd.bucket.sync='s3cmd sync'
alias s3cmd.file.delete='s3cmd del '
alias s3cmd.file.get='s3cmd get '
alias s3cmd.file.list='s3cmd ls '
alias s3cmd.file.put='s3cmd put '
alias s3cmd.help='s3cmd -h'
alias s3cmd.size='s3cmd du'
alias screen='screen -e$'\''\026'\''v'
alias screen.blank='sleep 0.5 ; xset dpms force off '
alias ssh='ssh -X'
alias sys.date='date'
alias sys.system='uname'
alias user.delete='userdel'
alias user.id='id'
alias user.list='sort /etc/passwd'
alias user.me='whoami'
alias user.new='useradd'
alias user.properties='id'
alias user.stat='id'
alias variable.delete='unset'
alias variable.exported.list='declare -x'
alias variable.list='set'
alias variable.new='declare'
alias vi='vim'
alias xml='xmlstarlet'
alias yaml2json='ruby -rjson -ryaml -e '\''puts YAML::load(ARGF.read).to_json'\'''
alias json2yaml='ruby -rjson -ryaml -e '\''puts JSON.parse(ARGF.read).to_yaml(line_width: -1)'\'''

alias ls.json='stat --printf="{\"SELinux_context\":\"%C\",\"access_human\":\"%A\",\"access_octal\":\"%a\",\"atime_epoch\":\"%X\",\"atime_human\":\"%x\",\"birht_time_epoch\":\"%W\",\"birth_time_human\":\"%w\",\"block_count\":\"%b\",\"blocksize_bytes\":\"%B\",\"ctime_epoch\":\"%Z\",\"ctime_human\":\"%z\",\"device_decimal\":\"%d\",\"device_hex\":\"%D\",\"file_type\":\"%F\",\"gid\":\"%g\",\"group\":\"%G\",\"hardlink_count\":\"%h\",\"inode\":\"%i\",\"io_size_hint\":\"%o\",\"major_device_hex\":\"%t\",\"minor_device_hex\":\"%T\",\"mount_point\":\"%m\",\"mtime_epoch\":\"%Y\",\"mtime_human\":\"%y\",\"name\":\"%n\",\"name_dereferenced\":\"%N\",\"owner\":\"%U\",\"raw_hex\":\"%f\",\"size_bytes\":\"%s\",\"uid\":\"%u\"}" '

